-- Gram Panchayat Hiwargaon Pawasa - production database foundation
create extension if not exists pgcrypto;
create extension if not exists pg_trgm;
create extension if not exists vector;

create type public.app_role as enum ('citizen','super_admin','gram_sevak','sarpanch','deputy_sarpanch','tax_officer','water_operator','complaint_officer','content_editor','accountant','auditor');
create type public.app_status as enum ('draft','submitted','under_verification','documents_required','approved','rejected','certificate_issued');
create type public.complaint_status as enum ('submitted','assigned','in_progress','resolved','closed','reopened','rejected');
create type public.payment_status as enum ('created','pending','paid','failed','refunded');

create table public.roles(id uuid primary key default gen_random_uuid(), name public.app_role unique not null, description text, created_at timestamptz default now());
create table public.permissions(id uuid primary key default gen_random_uuid(), code text unique not null, description text);
create table public.role_permissions(role_id uuid references public.roles on delete cascade, permission_id uuid references public.permissions on delete cascade, primary key(role_id,permission_id));
create table public.profiles(id uuid primary key references auth.users on delete cascade, full_name text not null, mobile text, date_of_birth date, gender text, address text, ward_no text, aadhaar_last4 text check(aadhaar_last4 is null or aadhaar_last4 ~ '^\d{4}$'), profile_photo_url text, preferred_language text default 'mr' check(preferred_language in ('mr','hi','en')), role public.app_role default 'citizen', is_active boolean default true, failed_login_count int default 0, locked_until timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.citizens(id uuid primary key default gen_random_uuid(), profile_id uuid unique references public.profiles on delete cascade, household_no text, ration_card_last4 text, occupation text, created_at timestamptz default now());
create table public.gram_panchayat_members(id uuid primary key default gen_random_uuid(), full_name text not null, designation text not null, ward_no text, photo_url text, phone text, message text, display_order int default 0, active boolean default true, created_at timestamptz default now());
create table public.staff(id uuid primary key default gen_random_uuid(), profile_id uuid references public.profiles, employee_code text unique, department text, designation text, active boolean default true, created_at timestamptz default now());

create table public.services(id uuid primary key default gen_random_uuid(), code text unique not null, title jsonb not null, description jsonb, fee numeric(12,2) default 0, processing_days int default 7, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.service_required_documents(id uuid primary key default gen_random_uuid(), service_id uuid references public.services on delete cascade, document_name jsonb not null, required boolean default true, max_size_mb int default 5, allowed_types text[] default array['application/pdf','image/jpeg','image/png'], unique(service_id,document_name));
create table public.applications(id uuid primary key default gen_random_uuid(), application_no text unique not null, citizen_id uuid references public.citizens, service_id uuid references public.services, applicant_snapshot jsonb not null, status public.app_status default 'draft', admin_remarks text, rejection_reason text, submitted_at timestamptz, approved_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create index applications_citizen_status_idx on public.applications(citizen_id,status);
create index applications_no_trgm_idx on public.applications using gin(application_no gin_trgm_ops);
create table public.application_documents(id uuid primary key default gen_random_uuid(), application_id uuid references public.applications on delete cascade, document_type text not null, storage_path text not null, file_name text not null, mime_type text, verified boolean default false, uploaded_at timestamptz default now());
create table public.application_status_history(id bigint generated always as identity primary key, application_id uuid references public.applications on delete cascade, old_status public.app_status, new_status public.app_status not null, remarks text, changed_by uuid references public.profiles, created_at timestamptz default now());
create table public.certificates(id uuid primary key default gen_random_uuid(), certificate_no text unique not null, application_id uuid unique references public.applications, certificate_type text not null, citizen_id uuid references public.citizens, public_payload jsonb not null, pdf_storage_path text, qr_token uuid unique default gen_random_uuid(), issued_by uuid references public.profiles, issued_at timestamptz default now(), revoked_at timestamptz);

create table public.properties(id uuid primary key default gen_random_uuid(), property_no text unique not null, owner_name text not null, citizen_id uuid references public.citizens, mobile text, address text not null, ward_no text, property_type text, construction_type text, area_sqft numeric(12,2), annual_tax numeric(12,2) default 0, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create index properties_search_idx on public.properties using gin((property_no||' '||owner_name||' '||coalesce(mobile,'')) gin_trgm_ops);
create table public.property_bills(id uuid primary key default gen_random_uuid(), bill_no text unique not null, property_id uuid references public.properties, financial_year text not null, annual_tax numeric(12,2) default 0, previous_dues numeric(12,2) default 0, penalty numeric(12,2) default 0, discount numeric(12,2) default 0, total_amount numeric(12,2) generated always as (annual_tax+previous_dues+penalty-discount) stored, due_date date, status text default 'unpaid', created_at timestamptz default now(), unique(property_id,financial_year));
create table public.water_connections(id uuid primary key default gen_random_uuid(), consumer_no text unique not null, property_id uuid references public.properties, citizen_id uuid references public.citizens, consumer_name text not null, meter_no text unique, connection_type text, active boolean default true, created_at timestamptz default now());
create table public.water_meter_readings(id uuid primary key default gen_random_uuid(), connection_id uuid references public.water_connections on delete cascade, billing_period date not null, previous_reading numeric(12,2) default 0, current_reading numeric(12,2) not null, usage numeric(12,2) generated always as (current_reading-previous_reading) stored, captured_by uuid references public.profiles, photo_path text, created_at timestamptz default now(), unique(connection_id,billing_period));
create table public.water_bills(id uuid primary key default gen_random_uuid(), bill_no text unique not null, connection_id uuid references public.water_connections, meter_reading_id uuid references public.water_meter_readings, billing_period date not null, current_charge numeric(12,2) default 0, previous_dues numeric(12,2) default 0, penalty numeric(12,2) default 0, total_amount numeric(12,2) generated always as (current_charge+previous_dues+penalty) stored, due_date date, status text default 'unpaid', created_at timestamptz default now(), unique(connection_id,billing_period));

create table public.payments(id uuid primary key default gen_random_uuid(), payment_no text unique not null, citizen_id uuid references public.citizens, bill_type text not null, bill_id uuid not null, amount numeric(12,2) not null check(amount>0), status public.payment_status default 'created', razorpay_order_id text unique, razorpay_payment_id text unique, transaction_id text, refund_status text, idempotency_key text unique not null, paid_at timestamptz, created_at timestamptz default now());
create index payments_created_idx on public.payments(created_at desc);
create table public.payment_receipts(id uuid primary key default gen_random_uuid(), payment_id uuid unique references public.payments on delete cascade, receipt_no text unique not null, pdf_storage_path text, emailed_at timestamptz, sms_sent_at timestamptz, created_at timestamptz default now());
create table public.payment_webhooks(id bigint generated always as identity primary key, provider text default 'razorpay', event_id text unique, event_type text, signature text, payload jsonb not null, processed boolean default false, error text, received_at timestamptz default now());

create table public.complaints(id uuid primary key default gen_random_uuid(), complaint_no text unique not null, citizen_id uuid references public.citizens, anonymous boolean default false, category text not null, description text not null, location_text text, latitude numeric(10,7), longitude numeric(10,7), priority text default 'medium', department text, assigned_officer uuid references public.profiles, status public.complaint_status default 'submitted', resolution_notes text, feedback text, rating int check(rating between 1 and 5), created_at timestamptz default now(), updated_at timestamptz default now());
create table public.complaint_attachments(id uuid primary key default gen_random_uuid(), complaint_id uuid references public.complaints on delete cascade, storage_path text not null, attachment_type text, stage text default 'before', created_at timestamptz default now());
create table public.complaint_status_history(id bigint generated always as identity primary key, complaint_id uuid references public.complaints on delete cascade, old_status public.complaint_status, new_status public.complaint_status not null, remarks text, changed_by uuid references public.profiles, created_at timestamptz default now());

create table public.notices(id uuid primary key default gen_random_uuid(), title jsonb not null, body jsonb, category text, attachment_path text, pinned boolean default false, publish_at timestamptz default now(), expire_at timestamptz, status text default 'published', created_by uuid references public.profiles, created_at timestamptz default now());
create table public.news(id uuid primary key default gen_random_uuid(), title jsonb not null, body jsonb, cover_image_path text, publish_at timestamptz default now(), expire_at timestamptz, status text default 'published', created_by uuid references public.profiles, created_at timestamptz default now());
create table public.events(id uuid primary key default gen_random_uuid(), title jsonb not null, description jsonb, venue text, starts_at timestamptz, ends_at timestamptz, attachment_path text, created_at timestamptz default now());
create table public.gram_sabha_meetings(id uuid primary key default gen_random_uuid(), title jsonb not null, meeting_at timestamptz not null, location text, agenda_document_path text, reminder_at timestamptz, status text default 'scheduled', created_at timestamptz default now());
create table public.gram_sabha_agendas(id uuid primary key default gen_random_uuid(), meeting_id uuid references public.gram_sabha_meetings on delete cascade, citizen_id uuid references public.citizens, suggestion text not null, status text default 'submitted', created_at timestamptz default now());
create table public.gram_sabha_minutes(id uuid primary key default gen_random_uuid(), meeting_id uuid unique references public.gram_sabha_meetings on delete cascade, attendance jsonb, decisions jsonb, resolutions jsonb, minutes_document_path text, published_at timestamptz);
create table public.schemes(id uuid primary key default gen_random_uuid(), title jsonb not null, department text, category text, description jsonb, benefits jsonb, eligibility jsonb, required_documents jsonb, application_process jsonb, important_dates jsonb, official_url text, contact_info jsonb, publish_at timestamptz default now(), expire_at timestamptz, status text default 'published', created_at timestamptz default now());
create table public.development_projects(id uuid primary key default gen_random_uuid(), project_name jsonb not null, department text, description jsonb, location text, contractor text, sanctioned_amount numeric(14,2) default 0, spent_amount numeric(14,2) default 0, start_date date, expected_completion_date date, progress int default 0 check(progress between 0 and 100), status text default 'proposed', work_order_path text, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.project_updates(id uuid primary key default gen_random_uuid(), project_id uuid references public.development_projects on delete cascade, progress int check(progress between 0 and 100), status text, notes jsonb, image_paths text[], citizen_feedback text, created_by uuid references public.profiles, created_at timestamptz default now());
create table public.public_documents(id uuid primary key default gen_random_uuid(), title jsonb not null, category text not null, document_date date, storage_path text not null, public boolean default true, published_at timestamptz default now(), created_by uuid references public.profiles);
create table public.galleries(id uuid primary key default gen_random_uuid(), title jsonb not null, category text, cover_path text, created_at timestamptz default now());
create table public.gallery_items(id uuid primary key default gen_random_uuid(), gallery_id uuid references public.galleries on delete cascade, media_type text, storage_path text not null, thumbnail_path text, caption jsonb, captured_at date, display_order int default 0);
create table public.emergency_contacts(id uuid primary key default gen_random_uuid(), service_name jsonb not null, phone text not null, alternate_phone text, address text, display_order int default 0, active boolean default true);
create table public.chatbot_faqs(id uuid primary key default gen_random_uuid(), question jsonb not null, answer jsonb not null, category text, verification_required boolean default false, active boolean default true, created_at timestamptz default now());
create table public.chatbot_documents(id uuid primary key default gen_random_uuid(), title text not null, storage_path text not null, extracted_text text, embedding vector(1536), active boolean default true, created_at timestamptz default now());
create table public.notifications(id uuid primary key default gen_random_uuid(), profile_id uuid references public.profiles on delete cascade, type text not null, title jsonb not null, body jsonb, data jsonb, read_at timestamptz, channels text[] default array['in_app'], created_at timestamptz default now());
create table public.audit_logs(id bigint generated always as identity primary key, actor_id uuid references public.profiles, action text not null, table_name text, record_id text, old_data jsonb, new_data jsonb, ip inet, user_agent text, created_at timestamptz default now());
create table public.website_settings(key text primary key, value jsonb not null, public boolean default true, updated_by uuid references public.profiles, updated_at timestamptz default now());
create table public.translations(id uuid primary key default gen_random_uuid(), namespace text not null, key text not null, mr text, hi text, en text, updated_at timestamptz default now(), unique(namespace,key));
create table public.visitor_counts(day date primary key default current_date, count bigint default 0);
create table public.contact_messages(id uuid primary key default gen_random_uuid(), name text not null, email text, mobile text, subject text, message text not null, status text default 'new', created_at timestamptz default now());

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role <> 'citizen' and is_active)$$;
create or replace function public.is_super_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role='super_admin' and is_active)$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name,mobile,preferred_language,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',new.email,'Citizen'),new.phone,coalesce(new.raw_user_meta_data->>'preferred_language','mr'),'citizen'); insert into public.citizens(profile_id) values(new.id); return new; end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security; alter table public.applications enable row level security; alter table public.application_documents enable row level security; alter table public.certificates enable row level security; alter table public.properties enable row level security; alter table public.property_bills enable row level security; alter table public.water_connections enable row level security; alter table public.water_bills enable row level security; alter table public.payments enable row level security; alter table public.complaints enable row level security; alter table public.notifications enable row level security;
create policy profiles_self_read on public.profiles for select using(id=auth.uid() or public.is_admin());
create policy profiles_self_update on public.profiles for update using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
create policy applications_owner on public.applications for all using(citizen_id=(select id from public.citizens where profile_id=auth.uid()) or public.is_admin()) with check(citizen_id=(select id from public.citizens where profile_id=auth.uid()) or public.is_admin());
create policy application_docs_owner on public.application_documents for all using(exists(select 1 from public.applications a join public.citizens c on c.id=a.citizen_id where a.id=application_id and (c.profile_id=auth.uid() or public.is_admin())));
create policy certificates_owner on public.certificates for select using(citizen_id=(select id from public.citizens where profile_id=auth.uid()) or public.is_admin());
create policy properties_owner on public.properties for select using(citizen_id=(select id from public.citizens where profile_id=auth.uid()) or public.is_admin());
create policy property_bills_owner on public.property_bills for select using(exists(select 1 from public.properties p join public.citizens c on c.id=p.citizen_id where p.id=property_id and (c.profile_id=auth.uid() or public.is_admin())));
create policy water_connections_owner on public.water_connections for select using(citizen_id=(select id from public.citizens where profile_id=auth.uid()) or public.is_admin());
create policy water_bills_owner on public.water_bills for select using(exists(select 1 from public.water_connections w join public.citizens c on c.id=w.citizen_id where w.id=connection_id and (c.profile_id=auth.uid() or public.is_admin())));
create policy payments_owner on public.payments for select using(citizen_id=(select id from public.citizens where profile_id=auth.uid()) or public.is_admin());
create policy complaints_owner on public.complaints for all using(anonymous or citizen_id=(select id from public.citizens where profile_id=auth.uid()) or public.is_admin()) with check(citizen_id=(select id from public.citizens where profile_id=auth.uid()) or public.is_admin());
create policy notifications_owner on public.notifications for select using(profile_id=auth.uid() or public.is_admin());

-- Public read-only content
alter table public.services enable row level security; alter table public.notices enable row level security; alter table public.news enable row level security; alter table public.events enable row level security; alter table public.gram_sabha_meetings enable row level security; alter table public.schemes enable row level security; alter table public.development_projects enable row level security; alter table public.project_updates enable row level security; alter table public.public_documents enable row level security; alter table public.galleries enable row level security; alter table public.gallery_items enable row level security; alter table public.emergency_contacts enable row level security; alter table public.website_settings enable row level security; alter table public.translations enable row level security;
create policy public_services_read on public.services for select using(active); create policy public_notices_read on public.notices for select using(status='published' and publish_at<=now() and (expire_at is null or expire_at>now())); create policy public_news_read on public.news for select using(status='published'); create policy public_events_read on public.events for select using(true); create policy public_meetings_read on public.gram_sabha_meetings for select using(true); create policy public_schemes_read on public.schemes for select using(status='published'); create policy public_projects_read on public.development_projects for select using(true); create policy public_project_updates_read on public.project_updates for select using(true); create policy public_documents_read on public.public_documents for select using(public); create policy public_galleries_read on public.galleries for select using(true); create policy public_gallery_items_read on public.gallery_items for select using(true); create policy public_emergency_read on public.emergency_contacts for select using(active); create policy public_settings_read on public.website_settings for select using(public); create policy public_translations_read on public.translations for select using(true);
-- Admin write policies
create policy admin_services_write on public.services for all using(public.is_admin()) with check(public.is_admin()); create policy admin_notices_write on public.notices for all using(public.is_admin()) with check(public.is_admin()); create policy admin_news_write on public.news for all using(public.is_admin()) with check(public.is_admin()); create policy admin_events_write on public.events for all using(public.is_admin()) with check(public.is_admin()); create policy admin_schemes_write on public.schemes for all using(public.is_admin()) with check(public.is_admin()); create policy admin_projects_write on public.development_projects for all using(public.is_admin()) with check(public.is_admin()); create policy admin_documents_write on public.public_documents for all using(public.is_admin()) with check(public.is_admin());

insert into public.roles(name) select unnest(enum_range(null::public.app_role)) on conflict do nothing;
insert into public.website_settings(key,value) values ('panchayat_profile','{"name_mr":"ग्रामपंचायत हिवरगाव पावसा","name_en":"Gram Panchayat Hiwargaon Pawasa","pin":"422605","map_url":"https://maps.app.goo.gl/3q2RxgoqDBkQAhfcA?g_st=ac"}') on conflict do nothing;

-- Government officials directory (national / state / district / local)
create table public.government_officials(id uuid primary key default gen_random_uuid(), full_name text not null, designation jsonb not null, level text not null check(level in ('national','state','district','local')), department text, photo_url text, official_url text, source text, last_verified date, display_order int default 0, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
alter table public.government_officials enable row level security;
create policy public_officials_read on public.government_officials for select using(active);
create policy admin_officials_write on public.government_officials for all using(public.is_admin()) with check(public.is_admin());

-- Meri Panchayat / eGramSwaraj / GPDP funding records, year-wise
create table public.funding_records(id uuid primary key default gen_random_uuid(), financial_year text not null unique, expected_funds numeric(14,2) default 0, funds_received numeric(14,2) default 0, previous_balance numeric(14,2) default 0, actual_expenditure numeric(14,2) default 0, tied_grants numeric(14,2) default 0, untied_grants numeric(14,2) default 0, cfc_grants numeric(14,2) default 0, sfc_grants numeric(14,2) default 0, own_source_revenue numeric(14,2) default 0, district_funds numeric(14,2) default 0, zp_funds numeric(14,2) default 0, ps_funds numeric(14,2) default 0, lgd_code text, data_status text default 'sample' check(data_status in ('sample','admin_verified','officially_imported','live')), official_source text, last_updated timestamptz default now(), created_at timestamptz default now());
alter table public.funding_records enable row level security;
create policy public_funding_read on public.funding_records for select using(true);
create policy admin_funding_write on public.funding_records for all using(public.is_admin()) with check(public.is_admin());

-- Year-wise Panchayat budget
create table public.budgets(id uuid primary key default gen_random_uuid(), financial_year text not null unique, opening_balance numeric(14,2) default 0, expected_income numeric(14,2) default 0, actual_income numeric(14,2) default 0, tax_income numeric(14,2) default 0, water_bill_income numeric(14,2) default 0, grant_income numeric(14,2) default 0, other_income numeric(14,2) default 0, planned_expenditure numeric(14,2) default 0, actual_expenditure numeric(14,2) default 0, audit_status text default 'Pending', audit_document_path text, created_at timestamptz default now());
alter table public.budgets enable row level security;
create policy public_budgets_read on public.budgets for select using(true);
create policy admin_budgets_write on public.budgets for all using(public.is_admin()) with check(public.is_admin());

insert into public.government_officials(full_name,designation,level,official_url,source,last_verified) values
 ('Droupadi Murmu','{"en":"President of India","mr":"भारताच्या राष्ट्रपती"}','national','https://www.presidentofindia.gov.in/','presidentofindia.gov.in','2026-08-01'),
 ('Narendra Modi','{"en":"Prime Minister of India","mr":"भारताचे पंतप्रधान"}','national','https://www.pmindia.gov.in/','pmindia.gov.in','2026-08-01'),
 ('Devendra Fadnavis','{"en":"Chief Minister of Maharashtra","mr":"महाराष्ट्राचे मुख्यमंत्री"}','state','https://www.maharashtra.gov.in/','maharashtra.gov.in','2026-08-01'),
 ('Eknath Shinde','{"en":"Deputy Chief Minister of Maharashtra","mr":"महाराष्ट्राचे उपमुख्यमंत्री"}','state','https://www.maharashtra.gov.in/','maharashtra.gov.in','2026-08-01'),
 ('Sunetra Pawar','{"en":"Deputy Chief Minister of Maharashtra","mr":"महाराष्ट्राचे उपमुख्यमंत्री"}','state','https://www.maharashtra.gov.in/','maharashtra.gov.in','2026-08-01')
on conflict do nothing;
