import { Menu, X, Phone, Search, Sun, Moon, LogIn, LogOut, Bot, Accessibility } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { useApp } from '../context/AppContext';
export function Layout({children}:{children:ReactNode}){const {t,lang,setLang,theme,toggleTheme,fontScale,setFontScale,user,logout}=useApp();const [open,setOpen]=useState(false);const nav=[['/',t('home')],['/services',t('services')],['/schemes',t('schemes')],['/notices',t('notices')],['/news','News'],['/projects',t('projects')],['/funding','Funding'],['/leadership','Leadership'],['/documents',t('documents')],['/gallery',t('gallery')],['/contact',t('contact')]];
return <div className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-slate-100">
<div className="bg-green-900 text-white text-xs px-4 py-2 flex justify-between"><span>महाराष्ट्र शासन • ग्रामीण विकास</span><span>Hiwargaon Pawasa, Maharashtra – 422605</span></div>
<header className="sticky top-0 z-40 bg-white/95 dark:bg-slate-900/95 shadow backdrop-blur"><div className="max-w-7xl mx-auto px-4 py-3 flex items-center gap-3"><Link to="/" className="flex items-center gap-3 min-w-0"><div className="h-12 w-12 rounded-full bg-gradient-to-br from-orange-500 via-white to-green-600 border grid place-items-center font-bold text-blue-900">GP</div><div className="min-w-0"><h1 className="font-bold text-green-900 dark:text-green-300 truncate">ग्रामपंचायत हिवरगाव पावसा</h1><p className="text-xs text-slate-500 truncate">Gram Panchayat Hiwargaon Pawasa</p></div></Link><div className="ml-auto flex items-center gap-1">
<select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as any)} className="input py-2"><option value="mr">मराठी</option><option value="hi">हिंदी</option><option value="en">English</option></select>
<button aria-label="Decrease font" onClick={()=>setFontScale(fontScale-.1)} className="icon-btn">A-</button><button aria-label="Increase font" onClick={()=>setFontScale(fontScale+.1)} className="icon-btn">A+</button><button aria-label="Theme" onClick={toggleTheme} className="icon-btn">{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><Link to="/search" className="icon-btn"><Search size={18}/></Link><Link to="/emergency" className="icon-btn text-red-600"><Phone size={18}/></Link>{user?<><Link to={user.role==='citizen'?'/dashboard':'/admin'} className="hidden md:inline-flex btn-secondary">{t('dashboard')}</Link><button onClick={logout} className="icon-btn"><LogOut size={18}/></button></>:<Link to="/login" className="hidden md:inline-flex btn-primary"><LogIn size={17}/>{t('login')}</Link>}<button onClick={()=>setOpen(!open)} className="icon-btn lg:hidden">{open?<X/>:<Menu/>}</button></div></div>
<nav className={`${open?'block':'hidden'} lg:block border-t dark:border-slate-700`}><div className="max-w-7xl mx-auto px-4 flex flex-col lg:flex-row">{nav.map(([to,label])=><NavLink onClick={()=>setOpen(false)} key={to} to={to} className={({isActive})=>`px-3 py-3 text-sm font-medium ${isActive?'text-green-700 border-b-2 border-green-600':'hover:text-green-700'}`}>{label}</NavLink>)}<NavLink to="/farmer" className="px-3 py-3 text-sm font-medium">शेतकरी सेवा</NavLink>{!user&&<Link to="/login" className="lg:hidden px-3 py-3">{t('login')}</Link>}</div></nav></header>
<div className="bg-orange-500 text-white overflow-hidden"><div className="ticker py-2 whitespace-nowrap">महत्त्वाची सूचना: ग्रामसभा, पाणीपुरवठा आणि कर भरणा संदर्भातील नवीन सूचना पाहण्यासाठी सूचना विभागाला भेट द्या. • Important notices are updated by the Gram Panchayat administration.</div></div>
<main>{children}</main><footer className="bg-slate-900 text-slate-200 mt-16"><div className="max-w-7xl mx-auto px-4 py-10 grid md:grid-cols-4 gap-8"><div><h3 className="font-bold text-white">ग्रामपंचायत हिवरगाव पावसा</h3><p className="text-sm mt-2">महाराष्ट्र – 422605</p></div><div><h4 className="font-semibold">Citizen Services</h4><Link className="footer-link" to="/apply">Apply online</Link><Link className="footer-link" to="/track">Track application</Link><Link className="footer-link" to="/pay">Pay bills</Link></div><div><h4 className="font-semibold">Transparency</h4><Link className="footer-link" to="/documents">Public documents</Link><Link className="footer-link" to="/projects">Development works</Link><Link className="footer-link" to="/gram-sabha">Gram Sabha</Link></div><div><h4 className="font-semibold">Location</h4><a className="footer-link" target="_blank" rel="noreferrer" href="https://maps.app.goo.gl/3q2RxgoqDBkQAhfcA?g_st=ac">Open Google Maps</a><p className="text-xs mt-4">© 2026 Gram Panchayat Hiwargaon Pawasa</p></div></div></footer><Link to="/chat" aria-label="GramMitra AI" className="fixed bottom-5 right-5 z-30 bg-green-700 text-white h-14 px-5 rounded-full shadow-xl flex items-center gap-2"><Bot/> ग्राममित्र AI</Link></div>}
