import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { Language, UserProfile } from '../types';
import { isSupabaseConfigured, supabase } from '../lib/supabase';
const strings={
 mr:{home:'मुख्यपृष्ठ',services:'सेवा',schemes:'योजना',notices:'सूचना',projects:'विकास कामे',documents:'सार्वजनिक कागदपत्रे',gallery:'गॅलरी',contact:'संपर्क',login:'लॉगिन',dashboard:'डॅशबोर्ड',admin:'प्रशासन',apply:'सेवेसाठी अर्ज',pay:'कर / बिल भरा',complaint:'तक्रार नोंदवा',track:'अर्ज स्थिती',welcome:'आपले गाव, आपला विकास'},
 hi:{home:'मुखपृष्ठ',services:'सेवाएँ',schemes:'योजनाएँ',notices:'सूचनाएँ',projects:'विकास कार्य',documents:'सार्वजनिक दस्तावेज',gallery:'गैलरी',contact:'संपर्क',login:'लॉगिन',dashboard:'डैशबोर्ड',admin:'प्रशासन',apply:'सेवा के लिए आवेदन',pay:'कर / बिल भुगतान',complaint:'शिकायत दर्ज करें',track:'आवेदन स्थिति',welcome:'हमारा गाँव, हमारा विकास'},
 en:{home:'Home',services:'Services',schemes:'Schemes',notices:'Notices',projects:'Development Works',documents:'Public Documents',gallery:'Gallery',contact:'Contact',login:'Login',dashboard:'Dashboard',admin:'Admin',apply:'Apply for Service',pay:'Pay Tax / Bill',complaint:'Register Complaint',track:'Track Application',welcome:'Our Village, Our Development'}
};
type Ctx={lang:Language;setLang:(l:Language)=>void;t:(k:keyof typeof strings.en)=>string;theme:string;toggleTheme:()=>void;fontScale:number;setFontScale:(n:number)=>void;user:UserProfile|null;loginDemo:(admin?:boolean)=>void;logout:()=>void;configured:boolean};
const Context=createContext<Ctx|null>(null);
export function AppProvider({children}:{children:ReactNode}){const [lang,setLangState]=useState<Language>(()=>(localStorage.getItem('gp_lang') as Language)||'mr');const [theme,setTheme]=useState(()=>localStorage.getItem('gp_theme')||'light');const [fontScale,setFontScaleState]=useState(Number(localStorage.getItem('gp_font')||1));const [user,setUser]=useState<UserProfile|null>(()=>{const v=localStorage.getItem('gp_user');return v?JSON.parse(v):null});
 useEffect(()=>{document.documentElement.classList.toggle('dark',theme==='dark');document.documentElement.style.fontSize=`${fontScale*100}%`;localStorage.setItem('gp_theme',theme);localStorage.setItem('gp_font',String(fontScale));},[theme,fontScale]);
 useEffect(()=>{if(!supabase)return; supabase.auth.getSession().then(({data})=>{if(data.session?.user){const u=data.session.user;setUser({id:u.id,full_name:u.user_metadata.full_name||u.email||'Citizen',email:u.email,role:(u.user_metadata.role||'citizen'),preferred_language:lang})}});},[]);
 const setLang=(l:Language)=>{setLangState(l);localStorage.setItem('gp_lang',l)}; const loginDemo=(admin=false)=>{const u:UserProfile={id:'demo',full_name:admin?'Demo Super Admin':'Demo Citizen',email:admin?'admin@demo.local':'citizen@demo.local',mobile:'9999999999',role:admin?'super_admin':'citizen',ward:'1',preferred_language:lang};setUser(u);localStorage.setItem('gp_user',JSON.stringify(u))}; const logout=()=>{setUser(null);localStorage.removeItem('gp_user');supabase?.auth.signOut()};
 const value=useMemo(()=>({lang,setLang,t:(k:keyof typeof strings.en)=>strings[lang][k],theme,toggleTheme:()=>setTheme(v=>v==='dark'?'light':'dark'),fontScale,setFontScale:(n:number)=>setFontScaleState(Math.max(.85,Math.min(1.25,n))),user,loginDemo,logout,configured:isSupabaseConfigured}),[lang,theme,fontScale,user]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useApp=()=>{const c=useContext(Context);if(!c)throw new Error('AppProvider missing');return c};
